members/urls.py
from django.urls import path
from .views import UserRegisterView

# app_name = 'memebers'
urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),

]

spellingapp/urls.py
from django.urls import path
from . import views


app_name = 'spellingapp'
urlpatterns = [
    path('', views.BaseView, name="home"),
    path('HomeView/', views.HomeView, name="HomeView" ),
    path('study/', views.study_view, name="study_view" ),
    path('learning/', views.learning_view, name="learning_view"),
    path('remove_key_val/<int:pk>/', views.remove_key_val, name='remove_key_val'),
    path('add_key_val/', views.add_key_val, name='add_key_val'),
    path('learning_add_key_val/', views.learning_add_key_val, name='learning_add_key_val'),
    path('fetch_get', views.fetch_get, name='fetch_get'),
]

spellingproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('spellingapp.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
]

members/models.py
from django.db import models

# Create your models here.

spellingapp/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse 
from datetime import datetime, date

class KeyVal(models.Model):
    word = models.CharField(max_length=240, default="word", null=True)
    spelling_error = models.CharField(max_length=240, default="spellingerror", null=True)

    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name='KeyVals', default='...')
    
    def __str__(self):
        return self.word   

members/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class SignUpForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')
        
    
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

members/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
# from .forms import SignUpForm

class UserRegisterView(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')

spellingapp/views.py
from django.core import paginator
from django.db import models
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.core.paginator import Paginator
# from django.views.generic import ListView, DetailView, DeleteView
from django.http import HttpResponseRedirect, HttpResponse, request, JsonResponse

from .models import KeyVal

import json

# Notes so I can push

def BaseView(request):
    return render(request, 'spellingapp/landing.html')

def HomeView(request):
    if KeyVal.objects == True:
        spelling_list = KeyVal.objects.filter(user=request.user)
    else:
        spelling_list = ''

    context = {
        'spelling_list': spelling_list,
    }
    return render(request, 'spellingapp/user_home.html', context)



def fetch_get(request):
    # all_data = KeyVal.objects.all()
    all_data = KeyVal.objects.filter(user=request.user)
    data_list = []
    for item in all_data:
        data_list.append({
            'word': item.word,
            'spelling_error': item.spelling_error,
        })

    return JsonResponse({'items': data_list})



def learning_view(request):
    spelling_list = KeyVal.objects.filter(user=request.user)
    
    context = {
        'spelling_list': spelling_list,
    }

    return render(request, 'spellingapp/learning.html', context)


def remove_key_val(request, pk):
    word_delete = get_object_or_404(KeyVal, pk=pk)
    word_delete.delete()
    return redirect('spellingapp:study_view')


def add_key_val(request):

    word = request.POST.get('word')
    if word == '':
        return redirect('spellingapp:study_view')
    else:
        spelling_error = request.POST.get('spelling_error')

        KeyVal.objects.create(
            spelling_error=spelling_error,
            word=word,
            user=request.user
        )

        return redirect('spellingapp:study_view')
    

def learning_add_key_val(request):
    keyVal_data = json.loads(request.body)
    word = keyVal_data['word']
    spelling_error = keyVal_data['spelling_error']
    user=request.user
    newKeyVal = KeyVal(word=word, spelling_error=spelling_error, user=user)
    newKeyVal.save()
    return HttpResponse('ok')

    

def study_view(request):
    spelling_list = KeyVal.objects.filter(user=request.user)
    paginator = Paginator(spelling_list, 20)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'spelling_list': page_obj,
    }
    return render(request, 'spellingapp/study_page.html', context )

spellingapp/templates/spellingapp/landing.html
{% extends 'spellingapp/base.html' %}
{% load static %}

{% block landing %}

<div id="landingPage">


    {% comment %} fixes some scenarios where gsap doesnt trigger when logged in but on base url {% endcomment %}
    {% if user.is_authenticated %}
        <div id="loggedHome">
            <h1 id="linguistLogged">Linguist </h1>
            <h1 id="assistLogged"><span> Assist</span></h1>
        </div>
        <div>
            <a id="loggedLearningLink" href="{% url 'spellingapp:learning_view' %}">Play</a>
            <a id="LoggedSpellingListLink" href="{% url 'spellingapp:study_view' %}">Spelling List</a>
        
        </div>
    {% else %}
        <div>
            <h1 id="linguist">Linguist </h1>
            <h1 id="assist"><span> Assist</span></h1>
        </div>
        <div id="homeLinks">
            <a id="homeLogLink" href="{% url 'login' %}">Login</a>
            <a id="homeRegLink" href="{% url 'register' %}">Register</a>
        </div>
    {% endif %}


</div>




{% endblock landing %} 

spellingapp/templates/spellingapp/learning.html
{% extends 'spellingapp/base.html' %}
{% load static %}

{% block learning %}

<div id="learningPage"> 
    <div id="preGameScreen">
        <h1 id="preGameH1">Select A Game</h1>
        <div id="preGameBtnContainer">

            <div id="gradeContainer">
                <p v-on:click="gradeMenuFunc" id="gradeSelect">By Grade <i id="caretGrade" class="fas fa-caret-right"> </i> </p>
                <div id="gradeMenu">
                    <p v-on:click="firstGradeFunc" id="firstGradeBtn">First Grade</p>
                    <p v-on:click="secondGradeFunc" id="secondGradeBtn">Second Grade</p>
                    <p v-on:click="thirdGradeFunc" id="thirdGradeBtn">Third Grade</p>

                    <p v-on:click="fourthGradeFunc" id="fourthGradeBtn">Fourth Grade</p>
                    <p v-on:click="fifthGradeFunc" id="fifthGradeBtn">Fifth Grade</p>
                    <p v-on:click="sixthGradeFunc" id="sixthGradeBtn">Sixth Grade</p>

                    <p v-on:click="seventhGradeFunc" id="seventhGradeBtn">Seventh Grade</p>
                    <p v-on:click="eighthGradeFunc" id="eighthGradeBtn">Eighth Grade</p>
                    <p v-on:click="ninthGradeFunc" id="ninthGradeBtn">Ninth Grade</p>
                </div>
            </div>

            <div id="easyContainer">
                <button id="easyBtn" class="preGameBtns" v-on:click="easyFunc">Easy</button>
                <p id="borderTopEasy"></p>
            </div>
         
            <div id="hardContainer">
                <button id="hardBtn" class="preGameBtns" v-on:click="hardFunc">Hard</button>
                <p id="borderTopHard"></p>
            </div>

            <div id="missedContainer">
                <button id="missedBtn" class="preGameBtns" v-on:click="missedFunc">Your Words</button>
                <p id="borderTopMissed"></p>
            </div>
        </div>
        <div id="pointsNeededContainer">
            <p id="pointsNTW">Adjust Points Needed:</p>
            <input id="inputRounds" type="number" value="10">
        </div>
        <p v-on:click="speechFunc" id="startBtn">play <span id="playIcon"><i class="fas fa-play"></i></span></p>
        <p id="noWordsInList">You can't choose 'Your Words' as you do not have an words in your <a href="{% url 'spellingapp:study_view' %}">Spelling List</a></p>
    </div>

    <div id="postGameScreen">
        <div id="postGameBtns">
            <a href="{% url 'spellingapp:learning_view' %}"><i class="fas fa-play"></i></a>
           <a href="{% url 'spellingapp:study_view' %}"><i class="fas fa-book"></i></a>
        </div>
        <div id="postGameContentDiv">
            <h1>Great Job!</h1>
            <p id="addedToList">The following words were added to your spelling list</p>
            <div id="flexRowForLoop">
                <div id="forLoopPostGame" v-for="item in stateWrongWords">
                    <p>[[item]]</p>
                </div>
            </div>
            <p id="noItemsMessage">You got all the words correct!</p>
        </div>
    </div>

    <div id="speechSelectContainer">
        <p  id="speechSelectLabel">Voice:</p>
        <select id="speechSelect"></select>
    </div>

        <p id="gameNameLabel">

    <div id="progressBarConatiner">
        <div id='progressBar'></div>

    </div>
    <div id="gameFace">
        <div id='defAndOld'>
            <h1>Definition</h1>
            <p v-on:click="hearDef" id='htmlDef'></p>
            <div v-on:click="hearDef">
                <i class="fas fa-volume-up"></i>
            </div>
        </div>

        {% csrf_token %}
        <input id="newWord" name="word" >
        <input v-on:keyup.enter="checkWord" type="text" id="inputValue" placeholder="Type Here" name="spelling_error" spellcheck="false">
        <div v-on:click="speechFunc" id="speachContainer">
            <p>Hear Word</p><p><i class="fas fa-volume-up"></i></p>
        </div>
        <button v-on:click="checkWord" id="checkWord" type="submit">Check Spelling</button>
    </div>

    <div id="lastTypo">
        <h3>Previous Typo</h3>
        <p> <span id="lastCorrect">Correct: [[lastCorrect]]</p></span>
        <p>Incorrect: [[lastError]]</p>
    </div> 
</div>

{% endblock learning %}

spellingapp/templates/spellingapp/study_page.html
{% extends 'spellingapp/base.html' %}
{% load static %}

{% block study %}
<div id="studyPage">

    <div id="studyPageInner">

            <section id="wordErrorLabel">
                <div>
                    <p id="wordLabel">Word</p>
                </div>
                <div>
                    <p id="errorLabel">Error</p>
                </div>
            </section>
        
            <form id="addAndRemoveForm" action="{% url 'spellingapp:add_key_val' %}" method="POST">
                {% csrf_token %}
                <input id="correctSpellingInput" type="text" name="word" placeholder="Correct Spelling">
                <input id="spellingErrorInput" type="text" name="spelling_error" placeholder="Incorrect Spelling">
                <br>
                <button id="addAndRemoveBtn" type="submit">Add To List</button>
            </form> 

            {% for item in spelling_list  %}
                <div id="spellingListContainer">
                    <div id="spellingListLeft">
                        <a id="removeWord" href="{% url 'spellingapp:remove_key_val' pk=item.pk %}"><i class="fas fa-eraser"></i></a>
                        <p>{{ item.word }}</p>
                    </div>
                    <div id="spellingListRight">
                        <p>{{ item.spelling_error }}</p>
                    </div>
                </div>
            {% endfor %}
            <br>
            
            <div class="pagination">
                <div class="step-links">
                    {% if spelling_list.has_previous %}
                        <div>
                            <a id="first" href="?page=1">&laquo; first</a>
                            <a id="previous" href="?page={{ spelling_list.previous_page_number }}">previous</a>
                        </div>
                    {% endif %}

                    <span class="current">
                        Page {{ spelling_list.number }} of {{ spelling_list.paginator.num_pages }}.
                    </span>
                    <div id="nextLastContainer">
                        {% if spelling_list.has_next %}
                            <a href="?page={{ spelling_list.next_page_number }}">next</a>
                            <a href="?page={{ spelling_list.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </div>
                </div>
            </div>
    </div>
</div>

{% endblock study %}

spellingapp/templates/spellingapp/user_home.html
{% extends 'spellingapp/base.html' %}
{% load static %}

{% block user_home %}
<p>user_home</p>

<a href="{% url 'spellingapp:HomeView' %}">
{% for item in spelling_list  %}
      <p>{{ item.word }}</p>
      <p>{{ item.spelling_error }}</p>
{% endfor %}

{% endblock user_home %}